algoritmo "soma"


var
   a, b, opcao: real

inicio
   escreva ("Digite o primeiro numero(a)")
   leia (a)

   escreva ("Digite o segundo numero(b)")
   leia (b)

   escreva ("Digite a operacao:")
   escreva ("1- soma, 2- subtracao, 3- multiplicacao")
   leia(opcao)

   se (opcao = 1) entao
   escreva a + b
   leia (numero a + b )

   se(opcao = 2) entao
   escreva a - b
   leia (numero - b)

   se(opcao = 3) entao
   escreva a * b
   leia (numero a * b)


fimalgoritmo
